<html lang="en">
<head>
    <base href="{BASE_URL}">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Instituto de Idiomas</title>
</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #f6f6f7;">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="docs/img/logo_institutoidiomas.jpg" alt="Bootstrap" width="135" height="90">
    </a>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Instituto de Idiomas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Idiomas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Profesores</a>
        </li>
      </ul>
      <span class="navbar-text">
      <a class="nav-link" href="#">Salir</a>
      </span>
    </div>
  </div>
</nav>
    
    
