
<form action="" method="POST" enctype="multipart/form-data" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control" 
                <?php if($idioma): ?> 
                    value="<?= htmlspecialchars($idioma->nombre) ?>"
                <?php endif ?> >
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Modulos</label>
                <select required name="modulos" class="form-control">
                    <option value="1" <?php if(($idioma) && ($idioma->modulos == 1)): ?>selected <?php endif?>>1</option>
                    <option value="2" <?php if(($idioma) && ($idioma->modulos == 2)): ?>selected <?php endif?>>2</option>
                    <option value="3" <?php if(($idioma) && ($idioma->modulos == 3)): ?>selected <?php endif?>>3</option>
                    <option value="4" <?php if(($idioma) && ($idioma->modulos == 4)): ?>selected <?php endif?>>4</option>
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Imagen</label>
        <input type="file" name="imput_name" id="imageToUpload">
    </div>

    <div class="form-group">
        <label>Descripción</label>
        <textarea name="descripcion" class="form-control" rows="3"><?php if($idioma): ?><?= htmlspecialchars($idioma->descripcion) ?><?php endif ?></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
