<form action="" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>seleccione idioma</label>
                <select required name="idioma" class="form-control">
                    <?php foreach($indiceIdiomas as $id => $idioma): ?>
                        <option value="<?= $id ?>"><?= $idioma ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Telefono</label>
        <textarea name="telefono" class="form-control" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label>Email</label>
        <textarea name="email" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>