<?php require 'templates/layouts/header.phtml' ?>



<ul class="list-group">
<?php foreach($profesores as $profesor): ?>
        <?php if ($profesor->imagen):?>
            <img src="<?= BASE_URL.$profesor->imagen ?>"/>
        <?php endif ?>

        <div class="label">
            <b><?= htmlspecialchars($profesor->nombre) ?></b> | <?=($profesor->telefono)?> | (<?= $profesor->email ?>)
        </div>
<?php endforeach ?>
</ul>

<?php require 'templates/layouts/footer.phtml' ?>
